version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monblog
    ports: ["3308:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BD/mon-blog.sql:/docker-entrypoint-initdb.d/init.sql

  apache:
    build: .
    depends_on: [mysql]
    ports: ["8081:80"]
    volumes: [.:/var/www/html]
    environment:
      DB_HOST: mysql
      DB_NAME: monblog
      DB_USER: root
      DB_PASSWORD: root

volumes:
  mysql_data: